name: logic4ads_ads
description: Logic4Ads Ads To create ads from logic4ads.com
version: 0.0.2
homepage: https://github.com/YSamer/logic4ads_ads

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
